export CUDA_VISIBLE_DEVICES=1

python inference_llava.py --model-path "/home/zyz/pretrained_models/LLaVa/full/llava-ShareGPT4V-7B" --folder-file "/home/zyz/dataset/ECCV_2024_data/data/train/skirt" --list-file "CoT_prompts_4/all_LLaVA_inputs/skirt/list_file.txt" > CoT_prompts_4/all_LLaVA_inputs/skirt/llava.txt
python inference_llava.py --model-path "/home/zyz/pretrained_models/LLaVa/full/llava-ShareGPT4V-7B" --folder-file "/home/zyz/dataset/ECCV_2024_data/data/train/sexy_kiss" --list-file "CoT_prompts_4/all_LLaVA_inputs/sexy_kiss/list_file.txt" > CoT_prompts_4/all_LLaVA_inputs/sexy_kiss/llava.txt
python inference_llava.py --model-path "/home/zyz/pretrained_models/LLaVa/full/llava-ShareGPT4V-7B" --folder-file "/home/zyz/dataset/ECCV_2024_data/data/train/sexy_implicit" --list-file "CoT_prompts_4/all_LLaVA_inputs/sexy_implicit/list_file.txt" > CoT_prompts_4/all_LLaVA_inputs/sexy_implicit/llava.txt
python inference_llava.py --model-path "/home/zyz/pretrained_models/LLaVa/full/llava-ShareGPT4V-7B" --folder-file "/home/zyz/dataset/ECCV_2024_data/data/train/sexy_imagetext" --list-file "CoT_prompts_4/all_LLaVA_inputs/sexy_imagetext/list_file.txt" > CoT_prompts_4/all_LLaVA_inputs/sexy_imagetext/llava.txt
python inference_llava.py --model-path "/home/zyz/pretrained_models/LLaVa/full/llava-ShareGPT4V-7B" --folder-file "/home/zyz/dataset/ECCV_2024_data/data/train/pout" --list-file "CoT_prompts_4/all_LLaVA_inputs/pout/list_file.txt" > CoT_prompts_4/all_LLaVA_inputs/pout/llava.txt
python inference_llava.py --model-path "/home/zyz/pretrained_models/LLaVa/full/llava-ShareGPT4V-7B" --folder-file "/home/zyz/dataset/ECCV_2024_data/data/train/middle_shoulders_and_belly" --list-file "CoT_prompts_4/all_LLaVA_inputs/middle_shoulders_and_belly/list_file.txt" > CoT_prompts_4/all_LLaVA_inputs/middle_shoulders_and_belly/llava.txt
python inference_llava.py --model-path "/home/zyz/pretrained_models/LLaVa/full/llava-ShareGPT4V-7B" --folder-file "/home/zyz/dataset/ECCV_2024_data/data/train/middle_normal" --list-file "CoT_prompts_4/all_LLaVA_inputs/middle_normal/list_file.txt" > CoT_prompts_4/all_LLaVA_inputs/middle_normal/llava.txt
python inference_llava.py --model-path "/home/zyz/pretrained_models/LLaVa/full/llava-ShareGPT4V-7B" --folder-file "/home/zyz/dataset/ECCV_2024_data/data/train/middle_leg" --list-file "CoT_prompts_4/all_LLaVA_inputs/middle_leg/list_file.txt" > CoT_prompts_4/all_LLaVA_inputs/middle_leg/llava.txt
python inference_llava.py --model-path "/home/zyz/pretrained_models/LLaVa/full/llava-ShareGPT4V-7B" --folder-file "/home/zyz/dataset/ECCV_2024_data/data/train/middle_hips" --list-file "CoT_prompts_4/all_LLaVA_inputs/middle_hips/list_file.txt" > CoT_prompts_4/all_LLaVA_inputs/middle_hips/llava.txt
