export CUDA_VISIBLE_DEVICES=7

python inference_llava.py --model-path "/home/zyz/pretrained_models/LLaVa/full/llava-ShareGPT4V-7B" --folder-file "/home/zyz/dataset/ECCV_2024_data/data/train/whole_shoulders_and_belly" --list-file "CoT_prompts_5/all_LLaVA_inputs/whole_shoulders_and_belly/list_file.txt" > CoT_prompts_5/all_LLaVA_inputs/whole_shoulders_and_belly/llava.txt
python inference_llava.py --model-path "/home/zyz/pretrained_models/LLaVa/full/llava-ShareGPT4V-7B" --folder-file "/home/zyz/dataset/ECCV_2024_data/data/train/whole_normal" --list-file "CoT_prompts_5/all_LLaVA_inputs/whole_normal/list_file.txt" > CoT_prompts_5/all_LLaVA_inputs/whole_normal/llava.txt
python inference_llava.py --model-path "/home/zyz/pretrained_models/LLaVa/full/llava-ShareGPT4V-7B" --folder-file "/home/zyz/dataset/ECCV_2024_data/data/train/whole_leg" --list-file "CoT_prompts_5/all_LLaVA_inputs/whole_leg/list_file.txt" > CoT_prompts_5/all_LLaVA_inputs/whole_leg/llava.txt
python inference_llava.py --model-path "/home/zyz/pretrained_models/LLaVa/full/llava-ShareGPT4V-7B" --folder-file "/home/zyz/dataset/ECCV_2024_data/data/train/whole_large_bare" --list-file "CoT_prompts_5/all_LLaVA_inputs/whole_large_bare/list_file.txt" > CoT_prompts_5/all_LLaVA_inputs/whole_large_bare/llava.txt
python inference_llava.py --model-path "/home/zyz/pretrained_models/LLaVa/full/llava-ShareGPT4V-7B" --folder-file "/home/zyz/dataset/ECCV_2024_data/data/train/whole_backless" --list-file "CoT_prompts_5/all_LLaVA_inputs/whole_backless/list_file.txt" > CoT_prompts_5/all_LLaVA_inputs/whole_backless/llava.txt
python inference_llava.py --model-path "/home/zyz/pretrained_models/LLaVa/full/llava-ShareGPT4V-7B" --folder-file "/home/zyz/dataset/ECCV_2024_data/data/train/wet" --list-file "CoT_prompts_5/all_LLaVA_inputs/wet/list_file.txt" > CoT_prompts_5/all_LLaVA_inputs/wet/llava.txt
python inference_llava.py --model-path "/home/zyz/pretrained_models/LLaVa/full/llava-ShareGPT4V-7B" --folder-file "/home/zyz/dataset/ECCV_2024_data/data/train/wearing_stockings" --list-file "CoT_prompts_5/all_LLaVA_inputs/wearing_stockings/list_file.txt" > CoT_prompts_5/all_LLaVA_inputs/wearing_stockings/llava.txt
python inference_llava.py --model-path "/home/zyz/pretrained_models/LLaVa/full/llava-ShareGPT4V-7B" --folder-file "/home/zyz/dataset/ECCV_2024_data/data/train/wearing_bras" --list-file "CoT_prompts_5/all_LLaVA_inputs/wearing_bras/list_file.txt" > CoT_prompts_5/all_LLaVA_inputs/wearing_bras/llava.txt
