# -*- coding: utf-8 -*-
import os

# save a list to a txt
def text_save(content, filename, mode = 'a'):
    # try to save a list variable in txt file.
    # Use the following command if Chinese characters are written (i.e., text in the file will be encoded in utf-8)
    file = open(filename, mode, encoding = 'utf-8')
    # file = open(filename, mode)
    for i in range(len(content)):
        file.write(str(content[i]) + '\n')
    file.close()

# read a txt expect EOF
def text_readlines(filename, mode = 'r'):
    # try to read a txt file and return a list.Return [] if there was a mistake.
    try:
        # Use the following command if there is Chinese characters are read
        file = open(filename, mode, encoding = 'utf-8')
        # file = open(filename, mode)
    except IOError:
        error = []
        return error
    content = file.readlines()
    # This for loop deletes the EOF (like \n)
    for i in range(len(content)):
        content[i] = content[i][:len(content[i]) - 1]
    file.close()
    return content

# post-process list generated by LLaVA (should have \n)
def post_process_llava(llava_list, name_list):
    llava_post_list = []
    temp = ''
    for j in range(len(llava_list)):
        if llava_list[j].split('/')[-1] not in name_list:
            if not llava_list[j].startswith('Prior information:'):
                if len(llava_list[j]) > 0:
                    temp = temp + llava_list[j] + ' '
        else:
            if temp:
                temp = temp.replace('1. ', '')
                temp = temp.replace('2. ', '')
                temp = temp.replace('</s>', '') # there is </s> at the end
                llava_post_list.append(temp.replace('  ', ' ').strip())
                temp = ''
            llava_post_list.append(llava_list[j].split('/')[-1])
    if temp:
        temp = temp.replace('1. ', '')
        temp = temp.replace('2. ', '')
        temp = temp.replace('</s>', '') # there is </s> at the end
        llava_post_list.append(temp.strip())
    return llava_post_list

if __name__ == '__main__':

    # run this after getting all results
    base_folder_path = '../CoT_prompts/addition_prompting_LLaVA_results'
    keywords = 'sexy_imagetext'
    llava_list = text_readlines(os.path.join(base_folder_path, keywords, 'llava.txt'))
    name_list = text_readlines(os.path.join(base_folder_path, keywords, 'name_list.txt'))
    
    # post-process lists
    # -------------------------------------------------
    llava_post_list = post_process_llava(llava_list, name_list)
    # -------------------------------------------------
    
    #text_save(llava_post_list, keywords + '.txt')

    post_temp_list = []
    for i in range(len(llava_post_list) // 2):
        post_temp_list.append(llava_post_list[i*2+1])
        post_temp_list.append(llava_post_list[i*2])
    text_save(post_temp_list, keywords + '.txt')
    