export CUDA_VISIBLE_DEVICES=2

python inference_llava.py --model-path "/home/zyz/pretrained_models/LLaVa/full/llava-ShareGPT4V-7B" --folder-file "/home/zyz/dataset/ECCV_2024_data/data/train/stockings" --list-file "CoT_prompts_2/all_LLaVA_inputs/stockings/list_file.txt" > CoT_prompts_2/all_LLaVA_inputs/stockings/llava.txt
python inference_llava.py --model-path "/home/zyz/pretrained_models/LLaVa/full/llava-ShareGPT4V-7B" --folder-file "/home/zyz/dataset/ECCV_2024_data/data/train/takeoff" --list-file "CoT_prompts_2/all_LLaVA_inputs/takeoff/list_file.txt" > CoT_prompts_2/all_LLaVA_inputs/takeoff/llava.txt
python inference_llava.py --model-path "/home/zyz/pretrained_models/LLaVa/full/llava-ShareGPT4V-7B" --folder-file "/home/zyz/dataset/ECCV_2024_data/data/train/tongue" --list-file "CoT_prompts_2/all_LLaVA_inputs/tongue/list_file.txt" > CoT_prompts_2/all_LLaVA_inputs/tongue/llava.txt
python inference_llava.py --model-path "/home/zyz/pretrained_models/LLaVa/full/llava-ShareGPT4V-7B" --folder-file "/home/zyz/dataset/ECCV_2024_data/data/train/upper_backless" --list-file "CoT_prompts_2/all_LLaVA_inputs/upper_backless/list_file.txt" > CoT_prompts_2/all_LLaVA_inputs/upper_backless/llava.txt
python inference_llava.py --model-path "/home/zyz/pretrained_models/LLaVa/full/llava-ShareGPT4V-7B" --folder-file "/home/zyz/dataset/ECCV_2024_data/data/train/upper_bust" --list-file "CoT_prompts_2/all_LLaVA_inputs/upper_bust/list_file.txt" > CoT_prompts_2/all_LLaVA_inputs/upper_bust/llava.txt
python inference_llava.py --model-path "/home/zyz/pretrained_models/LLaVa/full/llava-ShareGPT4V-7B" --folder-file "/home/zyz/dataset/ECCV_2024_data/data/train/upper_large_bare" --list-file "CoT_prompts_2/all_LLaVA_inputs/upper_large_bare/list_file.txt" > CoT_prompts_2/all_LLaVA_inputs/upper_large_bare/llava.txt
python inference_llava.py --model-path "/home/zyz/pretrained_models/LLaVa/full/llava-ShareGPT4V-7B" --folder-file "/home/zyz/dataset/ECCV_2024_data/data/train/upper_normal" --list-file "CoT_prompts_2/all_LLaVA_inputs/upper_normal/list_file.txt" > CoT_prompts_2/all_LLaVA_inputs/upper_normal/llava.txt
python inference_llava.py --model-path "/home/zyz/pretrained_models/LLaVa/full/llava-ShareGPT4V-7B" --folder-file "/home/zyz/dataset/ECCV_2024_data/data/train/upper_shoulders_and_belly" --list-file "CoT_prompts_2/all_LLaVA_inputs/upper_shoulders_and_belly/list_file.txt" > CoT_prompts_2/all_LLaVA_inputs/upper_shoulders_and_belly/llava.txt
