export CUDA_VISIBLE_DEVICES=0

python inference_llava.py --model-path "/home/zyz/pretrained_models/LLaVa/full/llava-ShareGPT4V-7B" --folder-file "/home/zyz/dataset/ECCV_2024_data/data/train/middle_crotch" --list-file "CoT_prompts_4/all_LLaVA_inputs/middle_crotch/list_file.txt" > CoT_prompts_4/all_LLaVA_inputs/middle_crotch/llava.txt
python inference_llava.py --model-path "/home/zyz/pretrained_models/LLaVa/full/llava-ShareGPT4V-7B" --folder-file "/home/zyz/dataset/ECCV_2024_data/data/train/male_sexy" --list-file "CoT_prompts_4/all_LLaVA_inputs/male_sexy/list_file.txt" > CoT_prompts_4/all_LLaVA_inputs/male_sexy/llava.txt
python inference_llava.py --model-path "/home/zyz/pretrained_models/LLaVa/full/llava-ShareGPT4V-7B" --folder-file "/home/zyz/dataset/ECCV_2024_data/data/train/lower_shoulders_and_belly" --list-file "CoT_prompts_4/all_LLaVA_inputs/lower_shoulders_and_belly/list_file.txt" > CoT_prompts_4/all_LLaVA_inputs/lower_shoulders_and_belly/llava.txt
python inference_llava.py --model-path "/home/zyz/pretrained_models/LLaVa/full/llava-ShareGPT4V-7B" --folder-file "/home/zyz/dataset/ECCV_2024_data/data/train/lower_normal" --list-file "CoT_prompts_4/all_LLaVA_inputs/lower_normal/list_file.txt" > CoT_prompts_4/all_LLaVA_inputs/lower_normal/llava.txt
python inference_llava.py --model-path "/home/zyz/pretrained_models/LLaVa/full/llava-ShareGPT4V-7B" --folder-file "/home/zyz/dataset/ECCV_2024_data/data/train/lower_leg" --list-file "CoT_prompts_4/all_LLaVA_inputs/lower_leg/list_file.txt" > CoT_prompts_4/all_LLaVA_inputs/lower_leg/llava.txt
python inference_llava.py --model-path "/home/zyz/pretrained_models/LLaVa/full/llava-ShareGPT4V-7B" --folder-file "/home/zyz/dataset/ECCV_2024_data/data/train/lower_large_bare" --list-file "CoT_prompts_4/all_LLaVA_inputs/lower_large_bare/list_file.txt" > CoT_prompts_4/all_LLaVA_inputs/lower_large_bare/llava.txt
python inference_llava.py --model-path "/home/zyz/pretrained_models/LLaVa/full/llava-ShareGPT4V-7B" --folder-file "/home/zyz/dataset/ECCV_2024_data/data/train/lower_hips" --list-file "CoT_prompts_4/all_LLaVA_inputs/lower_hips/list_file.txt" > CoT_prompts_4/all_LLaVA_inputs/lower_hips/llava.txt
python inference_llava.py --model-path "/home/zyz/pretrained_models/LLaVa/full/llava-ShareGPT4V-7B" --folder-file "/home/zyz/dataset/ECCV_2024_data/data/train/liftup" --list-file "CoT_prompts_4/all_LLaVA_inputs/liftup/list_file.txt" > CoT_prompts_4/all_LLaVA_inputs/liftup/llava.txt
python inference_llava.py --model-path "/home/zyz/pretrained_models/LLaVa/full/llava-ShareGPT4V-7B" --folder-file "/home/zyz/dataset/ECCV_2024_data/data/train/bite_lip" --list-file "CoT_prompts_4/all_LLaVA_inputs/bite_lip/list_file.txt" > CoT_prompts_4/all_LLaVA_inputs/bite_lip/llava.txt
python inference_llava.py --model-path "/home/zyz/pretrained_models/LLaVa/full/llava-ShareGPT4V-7B" --folder-file "/home/zyz/dataset/ECCV_2024_data/data/train/bite_finger" --list-file "CoT_prompts_4/all_LLaVA_inputs/bite_finger/list_file.txt" > CoT_prompts_4/all_LLaVA_inputs/bite_finger/llava.txt
